### ISSUE TITLE
Web view crash with profile.spall

### ISSUE THREAD

**Issue by SamWindell** [colrdavidson/spall-web#25]
Thanks for making this tool!

I had a go using spall_native_auto.h but the file it generates crashes the web view. Seems to happen even when I don't initialise any threads for profiling using spall_auto_thread_init(). 

I've attached the file. Let me know if you'd like anything more to reproduce it.

**Comment by SamWindell** [comment]
[profile.zip](https://github.com/colrdavidson/spall-web/files/11584698/profile.zip)

**Comment by colrdavidson** [comment]
Oops, my error message there needs a little work!

The native auto header only works with the native version of Spall, it's a different file format, and some of the things it does to compress the file like parse the traced executable and debug info for symbols, can't be done in-browser.

If you'd like to try auto-tracing, there is another version of the auto-tracer that'll work for the web client here: <https://github.com/colrdavidson/spall-web/tree/master/examples/auto_tracing>

If your trace is too big, and you'd prefer to mess with the native version of auto-tracing instead, that's on itch.io here: https://gravitymoth.itch.io/spall

**Comment by SamWindell** [comment]
Ah, thanks for the clarification. I'll take a look at the other options.
