### ISSUE TITLE
u64 version needed

### ISSUE THREAD

**Issue by SamWindell** [colrdavidson/spall-web#26]
Just been trying this code and came upon a minor issue. The 64-bit version of builtin_ctz is needed: __builtin_ctzll
Otherwise there is an implicit conversion to 32-bits and therefore an incorrect result.

https://github.com/colrdavidson/spall-web/blob/3f6be8a7dc7f6b170d4f9f2db00ee0a6df2bbd54/examples/auto_tracing/instrument.c#LL47C2-L47C2

**Comment by colrdavidson** [comment]
Ah, good catch! Thanks for the heads up, should be fixed now.
