### ISSUE TITLE
How to open profile.spall?

### ISSUE THREAD

**Issue by benner** [colrdavidson/spall-web#27]
Great project!

I've tried examples (e.g. native_auto_tracing) and cannot load profile.spall. I'm getting this:
![image](https://github.com/colrdavidson/spall-web/assets/407369/92494514-01d1-4d0c-9f0e-d395dadc7204)

What I'm doing wrong?

**Comment by colrdavidson** [comment]
Oops, my error message there needs a little work!

The native auto header only works with the native version of Spall, it's a different file format, and some of the things it does to compress the file like parse the traced executable and debug info for symbols, can't be done in-browser.

If you'd like to try auto-tracing, there is another version of the auto-tracer that'll work for the web client here: https://github.com/colrdavidson/spall-web/tree/master/examples/auto_tracing

If your trace is too big, and you'd prefer to mess with the native version of auto-tracing instead, that's on itch.io here: https://gravitymoth.itch.io/spall


I've removed the native auto tracer from the web version to avoid confusion, hopefully nobody else stumbles into this one.
