### ISSUE TITLE
Bug with long event names in spall.h

### ISSUE THREAD

**Issue by SamWindell** [colrdavidson/spall-web#28]
Hi again, got a minor fix here. 

The second memcpy within spall_build_begin() needs to use `trunc_name_len` instead of `name_len`

https://github.com/colrdavidson/spall-web/blob/17783521e15f1a063bf16a4742bef061553d2de3/spall.h#LL276C35-L276C35

**Comment by colrdavidson** [comment]
Oops! good catch, fixed.
