### ISSUE TITLE
Cannot load speedscope trace

### ISSUE THREAD

**Issue by daviddeutsch** [colrdavidson/spall-web#29]
I've got this small trace (~11MB) that I can check with speedscope just fine, but when I upload it into the Spall Web demo, I get:

    Your JSON file is invalid! got 6, expected [ or {

I don't see any issue with the json, though and since speedscope can load it just fine, I don't think it's that.

Anything I can do to help figure out what the problem is, here?

**Comment by daviddeutsch** [comment]
I took another shot at this and tried a _very_ small speedscope trace - barely 9kb

This time, I got no error, but the resulting view is entirely blank.

[traces.speedscope.zip](https://github.com/colrdavidson/spall-web/files/11904176/traces.speedscope.zip)

**Comment by colrdavidson** [comment]
Hey, looked into this today.

This looks like the speedscope specific trace format described here:
https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources

Spall supports the chrome://tracing format, and the chrome sampling profiler formats, but not this one. Unfortunately, I don't have plans to support Speedscope's format, but hopefully Speedscope can cover your needs.

**Comment by daviddeutsch** [comment]
Ah, ok - understood.

I actually converted it to the speedscope format, the original was a phpspy trace. I'm going to look into converting that into a suitable json representation!
