### ISSUE TITLE
Light mode default

### ISSUE THREAD

**Issue by hotgluebanjo** [colrdavidson/spall-web#30]
https://github.com/colrdavidson/spall-web/blob/5129ce6778a9d732a7de727a79648a71d1092962/src/spall.js#L622-L638

Should auto colors be the default setting? It's defaulting to light for me, where auto is the next in the cycle.

**Comment by hotgluebanjo** [comment]
Ah! Just need to check for `null` instead of `""`. Something like this fixes it:

```js
if (color_ret === null) {
	sessionStorage.setItem("colormode", "auto");
	color_ret = "auto";
}
```

**Comment by colrdavidson** [comment]
oh, oops!
good catch, yeah, it shouldn't be doing that, I'll take a look and apply the fix forward.
Appreciate it!
