### ISSUE TITLE
Unable to load Spall

### ISSUE THREAD

**Issue by patrickbard** [colrdavidson/spall-web#31]
I have the most recent version of Odin and just downloaded Spall, but I'm unable to use it.

Whenever I try to load `http://localhost:8000/spall.html` I got this message:

![image](https://github.com/colrdavidson/spall-web/assets/3281217/efa9b8fd-b746-4697-ad36-6ad5f4a60468)

Looking at browser console, I got this message:

    LinkError: WebAssembly.instantiate(): Import #5 module="env" function="fmax": function import requires a callable
    init @ spall.js:385

Then a little later there's another error:

    Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by heavyrain266** [comment]
Same here, in Firefox's console I'm getting:

```
LinkError: import object field 'fmax' is not a Function
```

**Comment by colrdavidson** [comment]
Thanks for the heads-up, I'll take a look.
Odin may have changed library function names a little

**Comment by Webzeez** [comment]
> I light entry ✨️ 😍 black2white , Amazing time space, and what matters upmost Highest =T rt UH mi Timo Ruth 4 truth.plus Extra Xt rawza  long voyage in views . The hub gits , got, on lead speed technology astronaut lol. Astronaut Reality ar zone Science and Truth word meet on 0 the highest point . The tip of tri. One 2 side / ..

Now we all see what T.W.H. was up on  top of a monster if ever was in luck # department no such , it is getting kocked down and back up again no matter what as for the Glory it out weighs the rest of con cast fake heapsplot mass GOT DG 0 up in drivers seat them lights up on High though.
"The Vision" the real Tim vision lights up a world 🌎 al Glory God first I take second place: for gifts this 01 receives 3rd place nominee on T meet Teeswitchesi0nX t web  proclaims his place in proper 💙....who who cans light. 


X straws Xtra 
3rd party's in relativity and 2nds in switch scale can swung pay bless 🙌 
Harvath Webster Timothy 
Anytime humble asking 
Thnx to all
Hello World 
Once more 
Dr. Dream 2 Reality 
TW0
ZH0
ZT0
0T
0
01
002
0002
The_Angels see that Swith bottoms the top Here THX truth

**Comment by colrdavidson** [comment]
Ok, try pulling Odin-master in again.
Looks like they had a few little bugs over the past few months that nobody had caught.

Helped them work through them, should be back in business again.
